### PR TITLE
Enhancements

### PR DESCRIPTION
**Pull request by Sommerregen**
This PR

- Fixes PHP coding standards issues (PSR1/2)
- Make the classes extendible (by changing the scope of private to protected methods)
- Implements code to automatically resolved language dependencies
- Addresses the issue of invalid regexes #15 
- Implements lazy-loading of language files
- Allows to fetch language files
- Simplifies code structure
- Adds docblocks

### CODE REVIEW

**Comment by S1SYPHOS** [comment]
From what I can grasp so far, this is a great PR, thank you very much for your in-depth work, which we'll more than happily review.

I guess @allejo will be thrilled, too :champagne:

**Comment by allejo** [comment]
Running the unit tests (`vendor/bin/phpunit`), I get a bunch of the following:

```
TODO, is this a relevant catch?
Exception: Language error ("array_flip(): Can only flip STRING and INTEGER values!") thrown from /private/tmp/highlight.php/Highlight/Highlighter.php:640 in /private/tmp/highlight.php/test/bootstrap.php:9
Stack trace:
#0 [internal function]: throwExceptionOnError(2, 'array_flip(): C...', '/private/tmp/hi...', 640, Array)
#1 /private/tmp/highlight.php/Highlight/Highlighter.php(640): array_flip(Array)
#2 /private/tmp/highlight.php/Highlight/Highlighter.php(583): Highlight\Highlighter->processSubLanguage()
#3 /private/tmp/highlight.php/Highlight/Highlighter.php(691): Highlight\Highlighter->processBuffer()
#4 /private/tmp/highlight.php/Highlight/Highlighter.php(289): Highlight\Highlighter->processLexeme('Hello, World!\n=...')
#5 /private/tmp/highlight.php/Highlight/Highlighter.php(335): Highlight\Highlighter->highlight('django', 'Hello, World!\n=...', false)
#6 /private/tmp/highlight.php/test/HighlightAutoTest.php(62): Highlight\Highlighter->highlightAuto('Hello, World!\n=...')
#7 [internal function]: HighlightAutoTest->testAutomaticDetection('asciidoc', 'Hello, World!\n=...')
#8 /private/tmp/highlight.php/vendor/phpunit/phpunit/src/Framework/TestCase.php(908): ReflectionMethod->invokeArgs(Object(HighlightAutoTest), Array)
#9 /private/tmp/highlight.php/vendor/phpunit/phpunit/src/Framework/TestCase.php(768): PHPUnit_Framework_TestCase->runTest()
#10 /private/tmp/highlight.php/vendor/phpunit/phpunit/src/Framework/TestResult.php(612): PHPUnit_Framework_TestCase->runBare()
#11 /private/tmp/highlight.php/vendor/phpunit/phpunit/src/Framework/TestCase.php(724): PHPUnit_Framework_TestResult->run(Object(HighlightAutoTest))
#12 /private/tmp/highlight.php/vendor/phpunit/phpunit/src/Framework/TestSuite.php(722): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult))
#13 /private/tmp/highlight.php/vendor/phpunit/phpunit/src/Framework/TestSuite.php(722): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#14 /private/tmp/highlight.php/vendor/phpunit/phpunit/src/Framework/TestSuite.php(722): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#15 /private/tmp/highlight.php/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(440): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#16 /private/tmp/highlight.php/vendor/phpunit/phpunit/src/TextUI/Command.php(149): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array)
#17 /private/tmp/highlight.php/vendor/phpunit/phpunit/src/TextUI/Command.php(100): PHPUnit_TextUI_Command->run(Array, true)
#18 /private/tmp/highlight.php/vendor/phpunit/phpunit/phpunit(52): PHPUnit_TextUI_Command::main()
#19 {main}
```

**Comment by scrivo** [comment]
Hi Benny

Thanks for sharing your pull request but I do have some second thoughts. Most things are you've done are not bad but are hardly improvements either. Throughout reading your changes I keep asking myself what are the actual issues you are trying to address. At the moment I do not know what I should do with your pull request, below you'll find my comments.

* Fixes PHP coding standards issues (PSR1/2)

All quotes used were double quotes (as I always do).
So (1) only one way of escaping is used throughout the package and (2) it is annoying when you add a variable in a string you'll have to change the quotes too. But this is a personal thing and may be changed, but I don't see the point.

Renaming local variables: $key is not arguably better than $k. These may be changed but again I don't see the point.

These changes make it really hard to compare code before and after the change.

* Make the classes extendible (by changing the scope of private to protected methods)

No way, I'm sorry. I'm not against to make members overridable but I'd like to have some use cases first. Most of the functions you make overridable are very specific for the implementation and are better kept private.

*  Implements code to automatically resolved language dependencies

I have no opinion about this issue.

*  Addresses the issue of invalid regexes #15

Highlight.php should not modify it's given regex expression, the language data needs to be correct. This will be the subject of another discussion.

*  Implements lazy-loading of language files

For what gain? For autodetection all (relevant) language definitions need to be loaded anyway. Highlight.php is a very demanding package in terms of CPU cycles but they are not burned while loading the languages. An optimisation might be to store them in a cache to reuse them in other requests but even that will have a neglectable result. 

But when talking about extendibility, it is here that you might want to override Highlight.php to change the default behaviour.

*  Allows to fetch language files

Ok, but what for: you can download them here on GitHub. Or am I missing something?

*  Simplifies code structure

What has been simplified?

*  Adds docblocks

Always good.

**Comment by Sommerregen** [comment]
Hi @S1SYPHOS, @allejo and @scrivo ,

First of all I should have run the unit test before. The `"array_flip(): Can only flip STRING and INTEGER values!"` message was indeed a bug and I also found two other minor issues. If you run the unit test again you will notice, that six of them will fail (the same tests as with the current master version). Those errors have to do with some style changes from the latest language definition JSON files and therefore the unit tests have to adjusted accordingly. If you like I can do it for you.

@scrivo Thanks for your detailed message and your criticism. I try to answer you as best as I can.

> All quotes used were double quotes (as I always do).

To be fair, PSR1/2 doesn't talk about quotes. However, more as a personal thing, single quotes should be favoured over double quotes. The reason: Double quotes start the string interpolation in PHP, which results in extra cpu cycles and higher memory consumption. You may have a look at the byte code to see what really happens. To be fair again, the speed-up is not seen in daily life. Even though it looks easy for you, it is simpler to stick to single quotes and use concatenation (which is faster as the string interpolation). As a bonus you'll get syntax highlighting and you directly see, which variable isused to build the string.

> Renaming local variables: $key is not arguably better than $k. These may be changed but again I don't see the point.

`$key` is indeed better than `$k`. Code should be self-descriptive. `$k` is definitely not. That's why most other programming languages will show you a notice. Also for other people, what should `$k` stands for? Especially, if you use other variables like `$x`, `$y`, `$u`, `$v` and use them wildly, it is not clear anymore, what the code does. Thus, `$key` is indeed more readable as `$k`. For the interpreter it doesn't change, so why not use it?

> No way, I'm sorry. I'm not against to make members overridable but I'd like to have some use cases first.

Well, to be honest that's the wrong approach. When writing classes you never know how they are used to be. Switching the scope from private to protected we allow the developer to write his own extensions without doubling the code. The use case. I use this library to highlight code. However there was no public function for getting all languages + aliases. That's why I sub-classed the highlighter and implemented the same language loading logic as the class already has, resulting in using twice as memory as really needed.
I also need some rules. That's why `getLanguage` has been changed to `public`.

You are right saying "most of the functions you make overridable are very specific for the implementation and are better kept private". However, please let the user decide, whether he or she needs them or not.

> Highlight.php should not modify it's given regex expression, the language data needs to be correct. This will be the subject of another discussion.

I totally agree with you. However, the current implementation has a bug. JavaScript regexes and PHP regexes differ; PHP needs regex boundaries. In the Language class the slash `/` is used. As @allejo already pointed out in #15 the slash in the middle of the regex `\d{4}([\.\\/:-]?\d{2}){0,5}` is treated as a boundary and breaks the regex. That's why all single slashes have to be escaped to be in consistent with the JavaScript equivalent. If you don't know what I'm talking about, take the above regex and try it out http://regex101.com/ .

> Implements lazy-loading of language files For what gain? For auto-detection all (relevant) language definitions need to be loaded anyway.

As I already have mentioned in the issue #15 there is no performance gain. As you said, the processing is the same. However it certainly makes a difference in memory consumption. The current version loads all language files into RAM, where this PR initializes the languages (grabs the name and the aliases only) and loads the language rules upon request. Thus, only the requested (auto-detected) languages are really in memory, not everything that is supported.

> Allows to fetch language files Ok, but what for: you can download them here on GitHub. Or am I missing something?

Again let the user decide. Use case: Provide a custom language, e.g., a language that detects markdown, HTML, Twig, and shortcodes. This is definitely not supported by the library. But the user is free to register his own language definition file.

> What has been simplified?

Lot's of if-else and break constructs and the fact, that only `$aliases` and `$languages` are needed. `$classMap` is merged into `$languages` now, making the code even a little bit faster as no `array_flip` in the `processSublanguage` method is needed anymore (not important in this discussion here).

In general, I'm open for ideas. If you don't like my contribution. Just say it. I'm totally fine with not publishing it and keeping a private fork instead. I just thought we could improve this excellent class a little more and provide features, that HighlightJS doesn't have. If you ask me, I'm also in favour of raising the requirement to PHP7 and make use of type hinting.

**Comment by S1SYPHOS** [comment]
As far as I'm concerned, we should not increase `Highlight.php`'s version requirement, simply because the (estimated) number of users using PHP 7.* is 'too damn ~~high~~ low' ([source](https://w3techs.com/technologies/details/pl-php/all/all)).

**Comment by allejo** [comment]
> Those errors have to do with some style changes from the latest language definitions and therefore the unit tests have to be adjusted accordingly. If you like I can do it for you.

I can't say I've looked into this, but if I recall correctly, the unit tests are directly ported from the JS project. So they shouldn't be something we fix manually in our own tests.

> Well, to be honest that's the wrong approach. When writing classes you never know how they are used to be. Switching the scope from private to protected we allow the developer to write his own extensions without doubling the code. The use case. I use this library to highlight code. However there was no public function for getting all languages + aliases. That's why I sub-classed the highlighter and implemented the same language loading logic as the class already has, resulting in using twice as memory as really needed.
I also need some rules. That's why getLanguage has been changed to public.

*Some* function privacy could be changed, however I stand by scrivo's decision in that not everything should be overwritten. As he mentioned, there's a lot of functionality that really has no need to be overridden. What features do you need that motivated this change? Narrowing down feature requests, we can rethink the design of the respective classes.

> You are right saying "most of the functions you make overridable are very specific for the implementation and are better kept private". However, please let the user decide, whether he or she needs them or not.

That's not how classes work...

> That's why all single slashes have to be escaped to be in consistent with the JavaScript equivalent.

Then the regular expressions should be changed/fixed in the process of porting them from the JS project; not in the library itself is my understanding of scrivo's statement.

> However it certainly makes a difference in memory consumption. The current version loads all language files into RAM, where this PR initializes the languages (grabs the name and the aliases only) and loads the language rules upon request. Thus, only the requested (auto-detected) languages are really in memory, not everything that is supported.

Automatic detection happens in a brute force manner. It will highlight the given code with **each** registered language and then it'll take the language with the highest accuracy. So in auto-detection, all languages eventually do get loaded into memory so lazy loading in this situation wouldn't be helpful.

> Provide a custom language, e.g., a language that detects markdown, HTML, Twig, and shortcodes. This is definitely not supported by the library. But the user is free to register his own language definition file.

That's the purpose of `Highlighter::registerLanguage()`, no? Or what do you mean specifically when it comes to fetching language files? I've built my own language definitions and have used them in highlighter.php (they're just not commited on here).

> In general, I'm open for ideas. If you don't like my contribution. Just say it. I'm totally fine with not publishing it and keeping a private fork instead. I just thought we could improve this excellent library a little more and provide features, that HighlightJS doesn't have. If you ask me, I'm also in favour of raising the requirement to PHP7 and make use of type hinting and dropping the dojo dependency in generating the language files.

- Same as s1syphos, I'm against bumping the minimum PHP version; there's no crucial need for this.
- I don't see dropping the dojo dependency in this PR? If there's a better way of translating JS definitions to our definitions, then I'm open to exploring it.

Overall, I think it'd be best to split this PR into more targetted changes.

**Pull request closed without merging**
