### PR TITLE
Fixed small mistake

### PR DESCRIPTION
**Pull request by pana1990**
Patch for this error : 

screenshot_1

### CODE REVIEW

**Comment by cebe** [comment]
very hard to review because of the whitespace changes. What really changed can be seen by disabling the whitespace: https://github.com/scrivo/highlight.php/pull/6/files?w=0

**Comment by pana1990** [comment]
thanks @cebe

**Comment by scrivo** [comment]
Not very critical indeed, but codewise a big glitch. Thanks!

**Comment by scrivo** [comment]
BTW pana1990 and cebe, I'll get rid of the trailing spaces for you in the next (pending) release ;)

**Comment by pana1990** [comment]
@scrivo ok, thanks!

**Pull request merged**
